In [1]:
import numpy as np

#### Broadcasting
product_names - название продуктов
price - цены на продукты
history - история покупок покупателями
names - имена покупателей

In [2]:
product_names = np.array(['хлеб','молоко','творог'])
product_names

array(['хлеб', 'молоко', 'творог'], dtype='<U6')

In [3]:
price = np.array([30,80,60])
price

array([30, 80, 60])

In [4]:
names = np.array(['Bob','Alice','Joe'])
names

array(['Bob', 'Alice', 'Joe'], dtype='<U5')

в строках покупки покупателей, в столбцах - продукты

In [5]:
history = np.array([[1,2,1],
                    [2,3,0],
                    [0,1,4]])
history

array([[1, 2, 1],
       [2, 3, 0],
       [0, 1, 4]])

Выбрать то что купил Bob

In [6]:
history[0,:]

array([1, 2, 1])

In [7]:
history[names=='Bob']

array([[1, 2, 1]])

Сколько хлеба купил Bob?

In [8]:
history[names=='Bob',product_names=='хлеб']

array([1])

sum_history - сумма покупок

In [9]:
sum_history = history * price
sum_history

array([[ 30, 160,  60],
       [ 60, 240,   0],
       [  0,  80, 240]])

На что потратил деньги Bob

In [10]:
sum_history[names=='Bob']

array([[ 30, 160,  60]])

Aggregation

общая потраченная сумма всеми покупателями

In [11]:
sum_history.sum()

870

сколько потратил каждый покупатель

In [12]:
sum_history.sum(axis=1)

array([250, 300, 320])

сколько потратил каждый на каждый продукт в сумме

In [13]:
sum_history.sum(axis=0)

array([ 90, 480, 300])

сколько потратил на все продукты Bob

In [14]:
sum_history.sum(axis=1)[names=='Bob']

array([250])

сколько люди потратили на творог

In [15]:
sum_history.sum(axis=0)[product_names=='творог']

array([300])

сколько в среднем люди постратили на каждый продукт

In [16]:
sum_history.mean(axis=0)

array([ 30., 160., 100.])

сколько минимум люди тратят на каждый продукт

In [17]:
sum_history.min(axis=0)

array([ 0, 80,  0])

сколько максимум люди тратят на каждый продукт

In [18]:
sum_history.max(axis=0)

array([ 60, 240, 240])

#### Объединение массивов

flats - таблица по квартирам которая имеет параметры: кол-во комнат, общая площадь, площадь кухни. Строки это сами квартиры
features - признаки квартиры
flat_id - id квартиры
price - цена квартиры
flats2 - аналог таблицы flats с доп столбцом цена

In [19]:
flats = np.array([[1,35,8],[1,38,10],[2,45,11],[3,65,12]])
flats

array([[ 1, 35,  8],
       [ 1, 38, 10],
       [ 2, 45, 11],
       [ 3, 65, 12]])

In [20]:
features = np.array(['Rooms','Square','KitchenSquare'])
features

array(['Rooms', 'Square', 'KitchenSquare'], dtype='<U13')

In [21]:
flat_id = np.array([123,124,125,180])
flat_id

array([123, 124, 125, 180])

In [22]:
price = np.array([3.5,3.7,5.5,7.2])
price

array([3.5, 3.7, 5.5, 7.2])

In [23]:
price = price.reshape(-1,1)
price

array([[3.5],
       [3.7],
       [5.5],
       [7.2]])

In [24]:
flats2 = np.hstack([flats,price])
flats2

array([[ 1. , 35. ,  8. ,  3.5],
       [ 1. , 38. , 10. ,  3.7],
       [ 2. , 45. , 11. ,  5.5],
       [ 3. , 65. , 12. ,  7.2]])

In [25]:
new_flat = np.array([4,75,15,12.5])
new_flat

array([ 4. , 75. , 15. , 12.5])

In [26]:
flats2 = np.vstack([flats2,new_flat])
flats2

array([[ 1. , 35. ,  8. ,  3.5],
       [ 1. , 38. , 10. ,  3.7],
       [ 2. , 45. , 11. ,  5.5],
       [ 3. , 65. , 12. ,  7.2],
       [ 4. , 75. , 15. , 12.5]])

высчитать сумму продажи всех квартир

In [27]:
flats2.sum(axis=0)[-1]

32.4

средняя цена продажи квартир

In [28]:
flats2[:,-1].mean()

6.4799999999999995

медиана продажи квартир

In [29]:
np.median(flats2[:,-1])

5.5

In [30]:
features2 = np.hstack([features,np.array(['Price'])])
features2

array(['Rooms', 'Square', 'KitchenSquare', 'Price'], dtype='<U13')

сколько комнат в квартирах

In [31]:
flats2[:,features2=='Rooms']

array([[1.],
       [1.],
       [2.],
       [3.],
       [4.]])

In [32]:
flats2[:,features2=='Rooms'].mean()

2.2

In [33]:
np.median(flats2[:,features2=='Rooms'])

2.0

In [34]:
new_flat2 = np.array([5, 85, 12, np.nan])
new_flat2

array([ 5., 85., 12., nan])

In [35]:
flats2 = np.vstack([flats2[:1],new_flat2,flats2[1:]])
flats2

array([[ 1. , 35. ,  8. ,  3.5],
       [ 5. , 85. , 12. ,  nan],
       [ 1. , 38. , 10. ,  3.7],
       [ 2. , 45. , 11. ,  5.5],
       [ 3. , 65. , 12. ,  7.2],
       [ 4. , 75. , 15. , 12.5]])

In [ ]:
np.array([i for i in flats2[:,-1] if not np.isnan(i)]).sum()
